const fs = require('fs');
let code = fs.readFileSync('app.html', 'utf8');

code = code.replace(
    '<div class="ad-placeholder adsbygoogle-container" style="margin-top: 1.5rem; background: var(--surface-low); border: 1px dashed var(--border-color); border-radius: 8px; padding: 1rem; text-align: center;">\n                    <div style="font-size: 0.65rem; color: var(--text-muted); text-transform: uppercase; margin-bottom: 0.5rem; letter-spacing: 1px;">SPONSOR_ADVERTISEMENT</div>\n                    <ins class="adsbygoogle"\n                         style="display:block; text-align:center;"\n                         data-ad-layout="in-article"\n                         data-ad-format="fluid"\n                         data-ad-client="ca-pub-4117687060036448"\n                         data-ad-slot="1234567890"></ins>',
    '<div class="ad-placeholder adsbygoogle-container" style="position: relative; margin-top: 1.5rem; background: var(--surface-low); border: 1px dashed var(--border-color); border-radius: 8px; padding: 1rem; text-align: center; min-height: 120px;">\n                    <div style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; display: flex; flex-direction: column; justify-content: center; align-items: center; z-index: 1; pointer-events: none;">\n                        <span class="material-symbols-outlined" style="color: var(--text-muted); opacity: 0.3; font-size: 24px; margin-bottom: 4px;">inventory_2</span>\n                        <span style="color: var(--text-muted); font-size: 0.7rem; font-family: var(--font-mono); opacity: 0.5; letter-spacing: 1px;">SPONSOR SPACE (PENDING)</span>\n                    </div>\n                    <ins class="adsbygoogle"\n                         style="position: relative; z-index: 2; display:block; text-align:center;"\n                         data-ad-layout="in-article"\n                         data-ad-format="fluid"\n                         data-ad-client="ca-pub-4117687060036448"\n                         data-ad-slot="1234567890"></ins>'
);

code = code.replace(
    '<div class="ad-sponsor-container" style="background: rgba(255,255,255,0.02); border: 1px dashed var(--primary); padding: 1.5rem 1rem; border-radius: 8px; margin: 1.5rem 0; position: relative;">\n                    <!-- Google AdSense Rewarded Popup Unit -->\n                    <ins class="adsbygoogle"\n                         style="display:block; width:100%; height:120px;"\n                         data-ad-client="ca-pub-4117687060036448"\n                         data-ad-slot="5678901234"\n                         data-ad-format="horizontal"\n                         data-full-width-responsive="true"></ins>',
    '<div class="ad-sponsor-container" style="background: rgba(255,255,255,0.02); border: 1px dashed var(--primary); padding: 0; border-radius: 8px; margin: 1.5rem 0; position: relative; min-height: 120px; display: flex; flex-direction: column; justify-content: flex-end;">\n                    <div style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; display: flex; flex-direction: column; justify-content: center; align-items: center; z-index: 1; pointer-events: none;">\n                        <span class="material-symbols-outlined" style="color: var(--primary); opacity: 0.5; font-size: 28px; margin-bottom: 8px;">campaign</span>\n                        <span style="color: var(--text-dim); font-size: 0.8rem; font-family: var(--font-mono); opacity: 0.8; letter-spacing: 1px;">PREMIUM AUDIO GEAR SPONSOR</span>\n                        <span style="color: var(--text-muted); font-size: 0.6rem; margin-top: 4px;">Ad verification pending...</span>\n                    </div>\n                    <!-- Google AdSense Rewarded Popup Unit -->\n                    <ins class="adsbygoogle"\n                         style="position: relative; z-index: 2; display:block; width:100%; height:120px;"\n                         data-ad-client="ca-pub-4117687060036448"\n                         data-ad-slot="5678901234"\n                         data-ad-format="horizontal"\n                         data-full-width-responsive="true"></ins>'
);

code = code.replace(
    '<div class="video-ad-container" style="position: relative; overflow: hidden; background: var(--surface-low); border: 1px dashed var(--border-color); border-radius: 8px; padding: 1.5rem 1rem; text-align: center; min-height: 150px; margin: 1.5rem 0;">\n                    <!-- Google AdSense Interstitial Popup Unit -->\n                    <ins class="adsbygoogle"\n                         style="display:block; width:100%; height:150px;"\n                         data-ad-client="ca-pub-4117687060036448"\n                         data-ad-slot="6789012345"\n                         data-ad-format="horizontal"\n                         data-full-width-responsive="true"></ins>',
    '<div class="video-ad-container" style="position: relative; overflow: hidden; background: var(--surface-low); border: 1px dashed var(--border-color); border-radius: 8px; padding: 0; text-align: center; min-height: 150px; margin: 1.5rem 0;">\n                    <div style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; display: flex; flex-direction: column; justify-content: center; align-items: center; z-index: 1; pointer-events: none;">\n                        <span class="material-symbols-outlined" style="color: var(--text-dim); opacity: 0.4; font-size: 32px; margin-bottom: 8px;">play_circle</span>\n                        <span style="color: var(--text-dim); font-size: 0.8rem; font-family: var(--font-mono); opacity: 0.7; letter-spacing: 1px;">SPONSORED SHOWCASE</span>\n                        <span style="color: var(--text-muted); font-size: 0.6rem; margin-top: 4px;">Awaiting Google AdSense Verification...</span>\n                    </div>\n                    <!-- Google AdSense Interstitial Popup Unit -->\n                    <ins class="adsbygoogle"\n                         style="position: relative; z-index: 2; display:block; width:100%; height:150px;"\n                         data-ad-client="ca-pub-4117687060036448"\n                         data-ad-slot="6789012345"\n                         data-ad-format="horizontal"\n                         data-full-width-responsive="true"></ins>'
);

code = code.replace(
    '<div id="bottom-sponsor-banner" class="ad-banner-bottom hidden">\n        <a href="#" target="_blank" class="sponsor-link">\n            <span class="sponsor-text">Sponsored by</span>\n            <img src="assets/img/sponsor-placeholder.png" alt="Sponsor Logo" class="sponsor-logo" onerror="this.style.display=\'none\';">\n        </a>\n    </div>',
    '<div id="bottom-sponsor-banner" class="ad-banner-bottom hidden">\n        <a href="#" target="_blank" class="sponsor-link" style="display: flex; align-items: center; justify-content: center; width: 100%; height: 100%;">\n            <div style="display: flex; align-items: center; justify-content: space-between; width: 100%; padding: 0 1rem;">\n                <span class="sponsor-text" style="font-size: 0.7rem; letter-spacing: 1px; color: var(--text-muted);">SPONSORED BY</span>\n                <div class="sponsor-placeholder" style="font-family: var(--font-headline); font-weight: bold; color: var(--primary); font-size: 1rem; letter-spacing: 2px;">\n                    SOUNDENGG PARTNERS\n                </div>\n                <span class="material-symbols-outlined" style="font-size: 16px; color: var(--text-muted);">open_in_new</span>\n            </div>\n        </a>\n    </div>'
);

fs.writeFileSync('app.html', code);
